### ISSUE TITLE
Error when build and run sample project..

### ISSUE THREAD

**Issue by IndieGameMaker** [googlevr/cardboard-xr-plugin#10]
When I tried build and run, getting a black screen after running the apk in Galaxy S9.
thus, I found error message in logcat.

I think used jballoffet user's absolute path .

Unity 2020.1.4f
IL2CPP

CardboardXRUnity [/Users/jballoffet/Documents/Workspace/cardboard/sdk/unity/xr_unity_plugin/cardboard_xr_unity.cc : 89] [/Users/jballoffet/Documents/Workspace/cardboard/sdk/unity/xr_unity_plugin/cardboard_xr_unity.cc : 572] GL error: 1282

**Comment by ZioCain** [comment]
I'm having a different error, but same procedure:
```
error: resource style/Theme.AppCompat.NoActionBar (aka <package_name>:style/Theme.AppCompat.NoActionBar) not found.
```

**Comment by jballoffet** [comment]
As explained in #1, please do not file issues here. Instead, file issues at https://github.com/googlevr/cardboard/issues.
As an exception, I personally moved this issue to googlevr/cardboard#108.
