### ISSUE TITLE
Google CardBoard XR plugin has some issue while building in xcode

### ISSUE THREAD

**Issue by monkeyMax-SVG** [googlevr/cardboard-xr-plugin#11]
while building in ios, i have some issue.
Please help me.

I am using following version
google cardboard xr plugin 1.1.0
Unity3D 2019.4.5f1
![image (6)](https://user-images.githubusercontent.com/54302680/92106260-b74a1c00-ee16-11ea-83b0-74f6b41b702e.png)
![image (7)](https://user-images.githubusercontent.com/54302680/92106278-bdd89380-ee16-11ea-93f8-3ad9fe51b683.png)

Thank you

**Comment by jballoffet** [comment]
As explained in #1, please do not file issues here. Instead, file issues at https://github.com/googlevr/cardboard/issues.
As an exception, I personally moved this issue to googlevr/cardboard#109.
