### ISSUE TITLE
Cardboard-XR Recenter issue

### ISSUE THREAD

**Issue by Angelium-hamza** [googlevr/cardboard-xr-plugin#14]
hello amazing people I am facing an issue regarding the Cardboard Recenter issue. 
i am using XRInputSubsystem.TryRecenter for recentering but it always returns false. and Cardboard camera is not recentered. 
i am using https://developers.google.com/cardboard/develop/unity/quickstart SDK.
thanks in advance.

**Comment by jballoffet** [comment]
Closing this as it is a duplicate of https://github.com/googlevr/cardboard/issues/176.
