### ISSUE TITLE
Objects that are out of sight in left eye, dissapear in right eye 

### ISSUE THREAD

**Issue by asierras** [googlevr/cardboard-xr-plugin#16]
Objects that are out of sight in left eye, dissapear in right eye. I cannot find a workaround and there is no single-pass or multi-pass option to check if it is due to that.

Here is a short video about it: https://streamable.com/vql157

**Comment by jballoffet** [comment]
As indicated in #1, please file issues at https://github.com/googlevr/cardboard/issues. You'll see this issue is a duplicate of #54.
