### ISSUE TITLE
Error OpenGl Unity 2020.2.0f1

### ISSUE THREAD

**Issue by Nand2com** [googlevr/cardboard-xr-plugin#17]
The console error is:

_"....cardboard_xr_unity.cc : 287] Misconfigured Graphics API. Neither OpenGl ES2.0 nor OpenGl ES3.0 was selected."

 In unity 2020.2.0f1(ios) there is no "auto graphics api" option to select opengles. Is there any method to add opengles to unity 2020? Will there be an update that is compatible with metal? . Thanks for everything!

**Comment by adamdavidcole** [comment]
Having the same issue! 

(Also to even get it to build, I had to add ArKit and then remove it)

**Comment by RGGuinness** [comment]
Same issue here with 2020.2.0f1(ios).  No options to select these for ios.  It is in the mac os config. 

[XR] [CardboardXrDisplayProvider]: Initializes Cardboard API.
[/Users/albachicar/localwork/release_v1_4_1/cardboard/sdk/unity/xr_unity_plugin/cardboard_xr_unity.cc : 287] Misconfigured Graphics API. Neither OpenGl ES2.0 nor OpenGl ES3.0 was selected.

**Comment by NDrexlAxonom** [comment]
Can confirm that I am getting this as well. Looks like the plugin needs to update to support metal to have this work since Unity deprecated OpenGL ES2.0/ES3.0 for iOS/macOS.

For now I will have to revert to Unity 2020.1

**Comment by jballoffet** [comment]
As indicated in #1, please file issues at https://github.com/googlevr/cardboard/issues. Unity 2020.2 requires Metal support, which is currently under active development. This is tracked by https://github.com/googlevr/cardboard/issues/11.
