### ISSUE TITLE
Bug where the position of the "X" button is changed in VR mode

### ISSUE THREAD

**Issue by guilecom** [googlevr/cardboard-xr-plugin#22]
platform: iOS
OS:

Problem: In VR mode, the position of the "X" button is recognized as a vertical SafeArea and displayed incorrectly.

There is a problem when entering VR mode after raising and lowering the notification bar by holding the device vertically.
(When entering VR mode, the rotation mode is always fixed to landscape)

**Comment by jballoffet** [comment]
As indicated in #1, please file issues at https://github.com/googlevr/cardboard/issues. Thanks!
