### ISSUE TITLE
Upgrading from legacy version of GVR to latest Google Cardboard SDK

### ISSUE THREAD

**Issue by lz7cjc** [googlevr/cardboard-xr-plugin#33]
Hi 
I need to upgrade beyond Unity v2019 so that I can build to API level 31 as dictated by Google Play
This means I need to upgrade the Google Cardboard SDK
I have followed the instructions and successfully built a new project. However this throws up two massive issues and I am hoping you can give me a solution

1. How do i control my app within the Unity Editor? Previously I used the GVRReticle pointer but there doesn't seem to be an equivalent to this in the upgraded version of the SDK. Obviously I don't want to have to build my app every time i need to check, test, or just experiment with something new
2.. The new system seems to rely on a specific *interactive* layer. The old system worked with colliders and event triggers. This together with the distance setting on the reticle pointer is how i have built my entire app; navigation, selection, everything. How do i replicate this system using the new SDK?

By blocking older versions of Android and changing the way the GVR Sdk works I appear to be stuck between a rock and a hard place and would very much appreciate some help in getting me out of this situation 

thanks

**Comment by jballoffet** [comment]
As indicated in https://github.com/googlevr/cardboard-xr-plugin/issues/1, please file issues at https://github.com/googlevr/cardboard/issues.

There you will find an issue template. Please fill it as thoroughly as possible.

We will be happy to provide help or guidance.

Thanks!
