### ISSUE TITLE
Parameters file not found for reading: java.io.FileNotFoundException: /storage/emulated/0/Cardboard/current_device params: open failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by techpin2** [googlevr/cardboard-xr-plugin#34]
### Error:
Parameters file not found for reading: java.io.FileNotFoundException: /storage/emulated/0/Cardboard/current_device params: open failed: ENOENT (No such file or directory)

We are getting above error in google cardboard xr plugin 1.22

### Scenario:
a. Install a new build
b. Scan monster cardboard qr code
c. Switch VR off on initial scene
d. Download asset bundle for vr game scene
e. On loading vr game scene : call EnterVR() function of VrModeController.cs (provided with sample hello cardboard scene)
f. the vr mode gets on but tracked pose driver won't work for gyro movement in android device as EnterVR() could not load current device params due to above error

### VERSIONS USED
Cardboard SDK/Cardboard XR Plugin 1.22
Unity Editor: 2021.3.23f1

**Comment by jballoffet** [comment]
As indicated in https://github.com/googlevr/cardboard-xr-plugin/issues/1, please file issues at https://github.com/googlevr/cardboard/issues.

There you will find an issue template. Please fill it as thoroughly as possible.

We will be happy to provide help or guidance.

Thanks!
