### ISSUE TITLE
DLLNotFoundException:cardboard_api

### ISSUE THREAD

**Issue by pithakoteTata** [googlevr/cardboard-xr-plugin#5]
Hi, 
When I try to use the "HelloCardboard" scene from Cardboard XR Plugin,  I get some errors. 
Some of them are:
1) When pressing "play" in editor the whole editor either crashes or I get this error
"DllNotFoundException: cardboard_api
Google.XR.Cardboard.Api.HasDeviceParams () (at Library/PackageCache/com.google.xr.cardboard@8979e065b7/Runtime/Api.cs:101)
"
2) Even if I just directly build and run to my Android device, it's just a black screen. 

I do not understand what I am doing wrong so if anyone can help please. 

I found this GitHub project that has built upon the Cardboard-XR-Plugin and I am having a play with it but I cannot seem to understand why those issues occured when I just tried the unedited Cardboard-XR-Plugin. 

The link to the improved GitHub Project: https://github.com/linojon/CardboardInteractor

**Comment by lonewolfaka9** [comment]
+1

**Comment by UnityKR** [comment]
Case 1.

modify CardboardStartup.cs
--------------------------------------------------
#if !UNITY_EDITOR
        if(!Api.HasDeviceParams())
        {
            Api.ScanDeviceParams();
        }
#endif
--------------------------------------------------

**Comment by UnityKR** [comment]
Case 1.

modify CardboardStartup.cs
--------------------------------------------------
#if !UNITY_EDITOR
        if(!Api.HasDeviceParams())
        {
            Api.ScanDeviceParams();
        }
#endif
--------------------------------------------------

**Comment by RoyGinsel** [comment]
Same problem gives black screen on android, works in unity when indeed adding the if !uniteditor
