### ISSUE TITLE
Error when importing this asset

### ISSUE THREAD

**Issue by knightcube** [googlevr/cardboard-xr-plugin#7]
When I tried importing this asset by following the instructions here - https://developers.google.com/cardboard/develop/unity/quickstart I got an error.
Here are the logs - ` error CS0234: The type or namespace name 'iOS' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)`

**Comment by knightcube** [comment]
I replaced the `#if UNITY_EDITOR` with `#if UNITY_IPHONE`. It resolves the error.

**Comment by whizzkid** [comment]
You probably did not include the IOS Build Support when installing unity.  
this plugin requires Android AND iOS build support to be present.

Add that, and it should work without changing the #if's

**Comment by knightcube** [comment]
I am also getting a black screen after running the apk in my phone

**Comment by whizzkid** [comment]
Make sure you're building using IL2CPP as scripting backend and not mono.

**Comment by knightcube** [comment]
I used IL2CPP but no luck

**Comment by whizzkid** [comment]
Did you import the sdk in a complete empty project?   if not, try that.
also try running the app on another device.

**Comment by knightcube** [comment]
I tried doing both of those. No luck.

**Comment by whizzkid** [comment]
what version of unity are you using? I've tried 2019.4.8f1 and it works.  otherwise I'm out of ideas..

**Comment by knightcube** [comment]
I am using Unity 2019.4

**Comment by jballoffet** [comment]
As explained in #1, please do not file issues here. Instead, file issues at https://github.com/googlevr/cardboard/issues.
As an exception, I personally moved this issue to googlevr/cardboard#105.
